import type { Plan } from "./plans";
const V2_PLUS_FEATURE = "Existing paid AI Leadership Suite entitlement";
const ALL_GRADES = ["Pre-K", "K", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"];
/** Read-only compatibility for existing paid subscribers. Never for sale or renewal. */
export const LEGACY_PLANS: Plan[] = [
  {
    id: "bundle_primary_plus_access",
    name: "Primary Plus Bundle",
    tagline: "Pre-K to Grade 5 with V2 intelligence",
    features: [
      "Pre-K-Grade 5, all subjects",
      "Up to 8 users",
      "3,500 AI credits/mo",
      V2_PLUS_FEATURE,
    ],
    restrictions: [
      "Single school",
      "Maximum 8 users (extra user: {extra_user_price})",
      "3,500 AI credits / month",
      "15 GB storage",
      "Priority email support",
      "AI Leadership Suite included",
    ],
    grades: ["Pre-K", "K", "1", "2", "3", "4", "5"],
    rank: 3,
    limits: {
      maxGrades: 7,
      maxSubjectsPerGrade: -1,
      maxUsers: 8,
      maxAcademicYears: 4,
      aiCreditsPerMonth: 3500,
      exportsPerMonth: 1500,
      storageGb: 75,
      maxCampuses: 1,
      teacherTraining: true,
      curriculumRecalibration: "standard",
      whiteLabel: false,
      apiAccess: false,
      dedicatedOnboarding: false,
      support: "Priority Email",
    },
    prices: [],
  },
  {
    id: "bundle_middle_plus_access",
    name: "Middle School Plus Bundle",
    tagline: "Grades 6-8 with V2 intelligence",
    features: [
      "Grades 6-8, all subjects",
      "Up to 14 users",
      "6,500 AI credits/mo",
      V2_PLUS_FEATURE,
    ],
    restrictions: [
      "Single school",
      "Maximum 14 users (extra user: {extra_user_price})",
      "6,500 AI credits / month",
      "30 GB storage",
      "Phone + email support",
      "AI Leadership Suite included",
    ],
    grades: ["6", "7", "8"],
    rank: 5,
    limits: {
      maxGrades: 3,
      maxSubjectsPerGrade: -1,
      maxUsers: 14,
      maxAcademicYears: 4,
      aiCreditsPerMonth: 6500,
      exportsPerMonth: 3500,
      storageGb: 150,
      maxCampuses: 1,
      teacherTraining: true,
      curriculumRecalibration: "advanced",
      whiteLabel: false,
      apiAccess: false,
      dedicatedOnboarding: false,
      support: "Phone + Email",
    },
    prices: [],
  },
  {
    id: "bundle_high_plus_access",
    name: "High School Plus Bundle",
    tagline: "Grades 9-12 with V2 intelligence",
    features: [
      "Grades 9-12, all subjects",
      "Up to 25 users",
      "10,000 AI credits/mo",
      V2_PLUS_FEATURE,
    ],
    restrictions: [
      "Single school",
      "Maximum 25 users (extra user: {extra_user_price})",
      "10,000 AI credits / month",
      "75 GB storage",
      "Board exam planning",
      "AI Leadership Suite included",
    ],
    grades: ["9", "10", "11", "12"],
    rank: 7,
    limits: {
      maxGrades: 4,
      maxSubjectsPerGrade: -1,
      maxUsers: 25,
      maxAcademicYears: 5,
      aiCreditsPerMonth: 10000,
      exportsPerMonth: 9000,
      storageGb: 300,
      maxCampuses: 1,
      teacherTraining: true,
      curriculumRecalibration: "advanced",
      whiteLabel: false,
      apiAccess: false,
      dedicatedOnboarding: false,
      support: "Phone + Email",
    },
    prices: [],
  },
  {
    id: "enterprise_plus_access",
    name: "Enterprise Plus",
    tagline: "Full K-12 with advanced V2 intelligence",
    features: [
      "All grades, all subjects",
      "Up to 100 users",
      "40,000 AI credits/mo",
      V2_PLUS_FEATURE,
    ],
    restrictions: [
      "1 campus included (extra campus: {extra_campus_price})",
      "Maximum 100 users (extra user: {extra_user_price})",
      "40,000 AI credits / month",
      "350 GB storage",
      "Dedicated account manager",
      "White-label branding",
      "API access",
      "AI Leadership Suite included",
    ],
    grades: "all",
    rank: 9,
    limits: {
      maxGrades: ALL_GRADES.length,
      maxSubjectsPerGrade: -1,
      maxUsers: 100,
      maxAcademicYears: 15,
      aiCreditsPerMonth: 40000,
      exportsPerMonth: 80000,
      storageGb: 500,
      maxCampuses: 1,
      teacherTraining: true,
      curriculumRecalibration: "advanced",
      whiteLabel: true,
      apiAccess: true,
      dedicatedOnboarding: true,
      support: "Dedicated Account Manager",
    },
    prices: [],
  },
];
