/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSeatsRouteImport } from './routes/_authenticated/seats'
import { Route as AuthenticatedPricingRouteImport } from './routes/_authenticated/pricing'
import { Route as AuthenticatedPartnerRouteImport } from './routes/_authenticated/partner'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAssignmentsRouteImport } from './routes/_authenticated/assignments'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSchoolProfileRouteImport } from './routes/_authenticated/school.profile'
import { Route as AuthenticatedResultsYearIdRouteImport } from './routes/_authenticated/results.$yearId'
import { Route as AuthenticatedAccountUsageRouteImport } from './routes/_authenticated/account.usage'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthenticatedCurriculumYearIdRescheduleRouteImport } from './routes/_authenticated/curriculum.$yearId.reschedule'
import { Route as AuthenticatedCurriculumYearIdProposeRouteImport } from './routes/_authenticated/curriculum.$yearId.propose'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSeatsRoute = AuthenticatedSeatsRouteImport.update({
  id: '/seats',
  path: '/seats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPricingRoute = AuthenticatedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartnerRoute = AuthenticatedPartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssignmentsRoute =
  AuthenticatedAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchoolProfileRoute =
  AuthenticatedSchoolProfileRouteImport.update({
    id: '/school/profile',
    path: '/school/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResultsYearIdRoute =
  AuthenticatedResultsYearIdRouteImport.update({
    id: '/results/$yearId',
    path: '/results/$yearId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountUsageRoute =
  AuthenticatedAccountUsageRouteImport.update({
    id: '/account/usage',
    path: '/account/usage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCurriculumYearIdRescheduleRoute =
  AuthenticatedCurriculumYearIdRescheduleRouteImport.update({
    id: '/curriculum/$yearId/reschedule',
    path: '/curriculum/$yearId/reschedule',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCurriculumYearIdProposeRoute =
  AuthenticatedCurriculumYearIdProposeRouteImport.update({
    id: '/curriculum/$yearId/propose',
    path: '/curriculum/$yearId/propose',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/partners': typeof PartnersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/partner': typeof AuthenticatedPartnerRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/seats': typeof AuthenticatedSeatsRoute
  '/account/usage': typeof AuthenticatedAccountUsageRoute
  '/results/$yearId': typeof AuthenticatedResultsYearIdRoute
  '/school/profile': typeof AuthenticatedSchoolProfileRoute
  '/curriculum/$yearId/propose': typeof AuthenticatedCurriculumYearIdProposeRoute
  '/curriculum/$yearId/reschedule': typeof AuthenticatedCurriculumYearIdRescheduleRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/partners': typeof PartnersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/partner': typeof AuthenticatedPartnerRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/seats': typeof AuthenticatedSeatsRoute
  '/account/usage': typeof AuthenticatedAccountUsageRoute
  '/results/$yearId': typeof AuthenticatedResultsYearIdRoute
  '/school/profile': typeof AuthenticatedSchoolProfileRoute
  '/curriculum/$yearId/propose': typeof AuthenticatedCurriculumYearIdProposeRoute
  '/curriculum/$yearId/reschedule': typeof AuthenticatedCurriculumYearIdRescheduleRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/partners': typeof PartnersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/assignments': typeof AuthenticatedAssignmentsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/partner': typeof AuthenticatedPartnerRoute
  '/_authenticated/pricing': typeof AuthenticatedPricingRoute
  '/_authenticated/seats': typeof AuthenticatedSeatsRoute
  '/_authenticated/account/usage': typeof AuthenticatedAccountUsageRoute
  '/_authenticated/results/$yearId': typeof AuthenticatedResultsYearIdRoute
  '/_authenticated/school/profile': typeof AuthenticatedSchoolProfileRoute
  '/_authenticated/curriculum/$yearId/propose': typeof AuthenticatedCurriculumYearIdProposeRoute
  '/_authenticated/curriculum/$yearId/reschedule': typeof AuthenticatedCurriculumYearIdRescheduleRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/partners'
    | '/reset-password'
    | '/admin'
    | '/assignments'
    | '/dashboard'
    | '/onboarding'
    | '/partner'
    | '/pricing'
    | '/seats'
    | '/account/usage'
    | '/results/$yearId'
    | '/school/profile'
    | '/curriculum/$yearId/propose'
    | '/curriculum/$yearId/reschedule'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/partners'
    | '/reset-password'
    | '/admin'
    | '/assignments'
    | '/dashboard'
    | '/onboarding'
    | '/partner'
    | '/pricing'
    | '/seats'
    | '/account/usage'
    | '/results/$yearId'
    | '/school/profile'
    | '/curriculum/$yearId/propose'
    | '/curriculum/$yearId/reschedule'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/partners'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/assignments'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/partner'
    | '/_authenticated/pricing'
    | '/_authenticated/seats'
    | '/_authenticated/account/usage'
    | '/_authenticated/results/$yearId'
    | '/_authenticated/school/profile'
    | '/_authenticated/curriculum/$yearId/propose'
    | '/_authenticated/curriculum/$yearId/reschedule'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PartnersRoute: typeof PartnersRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/seats': {
      id: '/_authenticated/seats'
      path: '/seats'
      fullPath: '/seats'
      preLoaderRoute: typeof AuthenticatedSeatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pricing': {
      id: '/_authenticated/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedPricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partner': {
      id: '/_authenticated/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof AuthenticatedPartnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assignments': {
      id: '/_authenticated/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthenticatedAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/school/profile': {
      id: '/_authenticated/school/profile'
      path: '/school/profile'
      fullPath: '/school/profile'
      preLoaderRoute: typeof AuthenticatedSchoolProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results/$yearId': {
      id: '/_authenticated/results/$yearId'
      path: '/results/$yearId'
      fullPath: '/results/$yearId'
      preLoaderRoute: typeof AuthenticatedResultsYearIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/usage': {
      id: '/_authenticated/account/usage'
      path: '/account/usage'
      fullPath: '/account/usage'
      preLoaderRoute: typeof AuthenticatedAccountUsageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/curriculum/$yearId/reschedule': {
      id: '/_authenticated/curriculum/$yearId/reschedule'
      path: '/curriculum/$yearId/reschedule'
      fullPath: '/curriculum/$yearId/reschedule'
      preLoaderRoute: typeof AuthenticatedCurriculumYearIdRescheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curriculum/$yearId/propose': {
      id: '/_authenticated/curriculum/$yearId/propose'
      path: '/curriculum/$yearId/propose'
      fullPath: '/curriculum/$yearId/propose'
      preLoaderRoute: typeof AuthenticatedCurriculumYearIdProposeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAssignmentsRoute: typeof AuthenticatedAssignmentsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPartnerRoute: typeof AuthenticatedPartnerRoute
  AuthenticatedPricingRoute: typeof AuthenticatedPricingRoute
  AuthenticatedSeatsRoute: typeof AuthenticatedSeatsRoute
  AuthenticatedAccountUsageRoute: typeof AuthenticatedAccountUsageRoute
  AuthenticatedResultsYearIdRoute: typeof AuthenticatedResultsYearIdRoute
  AuthenticatedSchoolProfileRoute: typeof AuthenticatedSchoolProfileRoute
  AuthenticatedCurriculumYearIdProposeRoute: typeof AuthenticatedCurriculumYearIdProposeRoute
  AuthenticatedCurriculumYearIdRescheduleRoute: typeof AuthenticatedCurriculumYearIdRescheduleRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAssignmentsRoute: AuthenticatedAssignmentsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPartnerRoute: AuthenticatedPartnerRoute,
  AuthenticatedPricingRoute: AuthenticatedPricingRoute,
  AuthenticatedSeatsRoute: AuthenticatedSeatsRoute,
  AuthenticatedAccountUsageRoute: AuthenticatedAccountUsageRoute,
  AuthenticatedResultsYearIdRoute: AuthenticatedResultsYearIdRoute,
  AuthenticatedSchoolProfileRoute: AuthenticatedSchoolProfileRoute,
  AuthenticatedCurriculumYearIdProposeRoute:
    AuthenticatedCurriculumYearIdProposeRoute,
  AuthenticatedCurriculumYearIdRescheduleRoute:
    AuthenticatedCurriculumYearIdRescheduleRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PartnersRoute: PartnersRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
